CREATE TABLE producto_variante (
                                   id_variante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   id_producto BIGINT NOT NULL
                                       REFERENCES producto(id_producto)
                                           ON DELETE CASCADE,

                                   nombre VARCHAR(80) NOT NULL,
                                   color_hex VARCHAR(7) NOT NULL,

                                   orden INT NOT NULL DEFAULT 0,
                                   activo BOOLEAN NOT NULL DEFAULT TRUE,

                                   fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
                                   fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                                   CONSTRAINT chk_producto_variante_color_hex
                                       CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$')
    );

CREATE INDEX idx_producto_variante_producto
    ON producto_variante(id_producto);

CREATE INDEX idx_producto_variante_producto_activo_orden
    ON producto_variante(id_producto, activo, orden);