CREATE TABLE usuario_admin (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(160) NOT NULL UNIQUE,
    nombre VARCHAR(120) NOT NULL,
    pass_hash TEXT NOT NULL,
    rol VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR(160) NOT NULL,
    precio NUMERIC(12, 2) NOT NULL CHECK (precio >= 0),
    descripcion TEXT,
    slug VARCHAR(190) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    marca VARCHAR(100),

    creado_por BIGINT REFERENCES usuario_admin(id_usuario),
    actualizado_por BIGINT REFERENCES usuario_admin(id_usuario),

    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE categoria (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(160) NOT NULL UNIQUE,
    slug VARCHAR(190) NOT NULL UNIQUE
);

CREATE TABLE producto_categoria (
    id_producto_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_producto BIGINT NOT NULL REFERENCES producto(id_producto) ON DELETE CASCADE,
    id_categoria BIGINT NOT NULL REFERENCES categoria(id_categoria) ON DELETE CASCADE,

    CONSTRAINT uq_producto_categoria UNIQUE (id_producto, id_categoria)
);

CREATE TABLE imagen_producto (
    id_imagen BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_producto BIGINT NOT NULL REFERENCES producto(id_producto) ON DELETE CASCADE,

    public_id VARCHAR(255),
    url TEXT NOT NULL,
    orden INT NOT NULL DEFAULT 0,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    alt_text VARCHAR(200),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_producto_orden UNIQUE (id_producto, orden)
);

CREATE TABLE producto_audit_log (
    id_producto_audit_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_producto BIGINT NOT NULL REFERENCES producto(id_producto) ON DELETE CASCADE,
    id_usuario BIGINT NOT NULL REFERENCES usuario_admin(id_usuario),

    accion VARCHAR(40) NOT NULL,
    detalle TEXT,
    fecha_evento TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_producto_creado_por
ON producto(creado_por);

CREATE INDEX idx_producto_actualizado_por
ON producto(actualizado_por);

CREATE INDEX idx_producto_categoria_producto
ON producto_categoria(id_producto);

CREATE INDEX idx_producto_categoria_categoria
ON producto_categoria(id_categoria);

CREATE INDEX idx_imagen_producto_producto
ON imagen_producto(id_producto);

CREATE INDEX idx_producto_audit_log_producto
ON producto_audit_log(id_producto);

CREATE INDEX idx_producto_audit_log_usuario
ON producto_audit_log(id_usuario);

CREATE UNIQUE INDEX uq_imagen_producto_principal
ON imagen_producto(id_producto)
WHERE principal = TRUE;