CREATE TABLE cliente (
                         id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         email VARCHAR(160) NOT NULL UNIQUE,
                         nombre VARCHAR(120) NOT NULL,
                         telefono VARCHAR(30) NOT NULL,
                         pass_hash TEXT NOT NULL,

                         activo BOOLEAN NOT NULL DEFAULT TRUE,

                         fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
                         fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_cliente_email
    ON cliente(email);

CREATE INDEX idx_cliente_activo
    ON cliente(activo);