CREATE TABLE cliente_favorito (
                                  id_cliente_favorito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  id_cliente BIGINT NOT NULL,
                                  id_producto BIGINT NOT NULL,

                                  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                                  CONSTRAINT fk_cliente_favorito_cliente
                                      FOREIGN KEY (id_cliente)
                                          REFERENCES cliente(id_cliente)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_cliente_favorito_producto
                                      FOREIGN KEY (id_producto)
                                          REFERENCES producto(id_producto)
                                          ON DELETE CASCADE,

                                  CONSTRAINT uq_cliente_favorito_cliente_producto
                                      UNIQUE (id_cliente, id_producto)
);

CREATE INDEX idx_cliente_favorito_cliente
    ON cliente_favorito(id_cliente);

CREATE INDEX idx_cliente_favorito_producto
    ON cliente_favorito(id_producto);