CREATE TABLE carrito (
                         id_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         id_cliente BIGINT NOT NULL,
                         estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',

                         fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
                         fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                         CONSTRAINT fk_carrito_cliente
                             FOREIGN KEY (id_cliente)
                                 REFERENCES cliente(id_cliente)
                                 ON DELETE CASCADE,

                         CONSTRAINT ck_carrito_estado
                             CHECK (estado IN ('ACTIVO', 'CERRADO', 'ABANDONADO'))
);

CREATE UNIQUE INDEX uq_carrito_activo_por_cliente
    ON carrito(id_cliente)
    WHERE estado = 'ACTIVO';

CREATE INDEX idx_carrito_cliente
    ON carrito(id_cliente);

CREATE INDEX idx_carrito_estado
    ON carrito(estado);


CREATE TABLE carrito_item (
                              id_carrito_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              id_carrito BIGINT NOT NULL,
                              id_producto BIGINT NOT NULL,

                              cantidad INTEGER NOT NULL,
                              precio_unitario_snapshot NUMERIC(12, 2) NOT NULL,

                              fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
                              fecha_ultima_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                              CONSTRAINT fk_carrito_item_carrito
                                  FOREIGN KEY (id_carrito)
                                      REFERENCES carrito(id_carrito)
                                      ON DELETE CASCADE,

                              CONSTRAINT fk_carrito_item_producto
                                  FOREIGN KEY (id_producto)
                                      REFERENCES producto(id_producto)
                                      ON DELETE RESTRICT,

                              CONSTRAINT ck_carrito_item_cantidad
                                  CHECK (cantidad > 0),

                              CONSTRAINT uq_carrito_item_carrito_producto
                                  UNIQUE (id_carrito, id_producto)
);

CREATE INDEX idx_carrito_item_carrito
    ON carrito_item(id_carrito);

CREATE INDEX idx_carrito_item_producto
    ON carrito_item(id_producto);