ALTER TABLE cliente
    ADD COLUMN email_verificado BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cliente
    ADD COLUMN fecha_email_verificado TIMESTAMPTZ;


CREATE TABLE cliente_email_verification_token (
                                                  id_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                  id_cliente BIGINT NOT NULL,
                                                  token_hash VARCHAR(64) NOT NULL UNIQUE,

                                                  expires_at TIMESTAMPTZ NOT NULL,
                                                  used_at TIMESTAMPTZ,
                                                  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                                                  CONSTRAINT fk_cliente_email_verification_token_cliente
                                                      FOREIGN KEY (id_cliente)
                                                          REFERENCES cliente(id_cliente)
                                                          ON DELETE CASCADE
);

CREATE INDEX idx_cliente_email_verification_token_cliente
    ON cliente_email_verification_token(id_cliente);

CREATE INDEX idx_cliente_email_verification_token_hash
    ON cliente_email_verification_token(token_hash);

CREATE INDEX idx_cliente_email_verification_token_expires_at
    ON cliente_email_verification_token(expires_at);