CREATE TABLE cliente_password_reset_token (
                                              id_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                              id_cliente BIGINT NOT NULL,
                                              token_hash VARCHAR(64) NOT NULL UNIQUE,

                                              expires_at TIMESTAMPTZ NOT NULL,
                                              used_at TIMESTAMPTZ,
                                              fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                                              CONSTRAINT fk_cliente_password_reset_token_cliente
                                                  FOREIGN KEY (id_cliente)
                                                      REFERENCES cliente(id_cliente)
                                                      ON DELETE CASCADE
);

CREATE INDEX idx_cliente_password_reset_token_cliente
    ON cliente_password_reset_token(id_cliente);

CREATE INDEX idx_cliente_password_reset_token_hash
    ON cliente_password_reset_token(token_hash);

CREATE INDEX idx_cliente_password_reset_token_expires_at
    ON cliente_password_reset_token(expires_at);