ALTER TABLE usuario_admin
    ADD COLUMN email_verificado BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE usuario_admin
    ADD COLUMN fecha_email_verificado TIMESTAMPTZ;

UPDATE usuario_admin
SET fecha_email_verificado = COALESCE(fecha_email_verificado, fecha_creacion)
WHERE email_verificado = TRUE;

CREATE TABLE admin_invitation_token (
                                        id_token BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                        id_usuario_admin BIGINT NOT NULL,
                                        token_hash VARCHAR(64) NOT NULL UNIQUE,

                                        expires_at TIMESTAMPTZ NOT NULL,
                                        used_at TIMESTAMPTZ,
                                        fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),

                                        CONSTRAINT fk_admin_invitation_token_usuario_admin
                                            FOREIGN KEY (id_usuario_admin)
                                                REFERENCES usuario_admin(id_usuario)
                                                ON DELETE CASCADE
);

CREATE INDEX idx_admin_invitation_token_usuario_admin
    ON admin_invitation_token(id_usuario_admin);

CREATE INDEX idx_admin_invitation_token_hash
    ON admin_invitation_token(token_hash);

CREATE INDEX idx_admin_invitation_token_expires_at
    ON admin_invitation_token(expires_at);